USE [SuperstoreBI]
GO

/****** Object:  Table [dw].[DimOrderPriority]    Script Date: 8/29/2026 11:32:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[DimOrderPriority](
	[OrderPriorityID] [int] IDENTITY(1,1) NOT NULL,
	[OrderPriority] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderPriorityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

