import pandas as pd
df=pd.read_csv("data/GlobalSuperstore.csv", encoding='ISO-8859-1')
df["Clean_order_date"]=pd.to_datetime(df["Clean_order_date"], format="mixed")
df["Clean_Ship_Date"]=pd.to_datetime(df["Clean_Ship_Date"], format="mixed")

print(df.head())
print(df.info())
print(df.shape)
print(df.columns)
print(df.isna().sum())
print(df["customer_name"].nunique())
print(df["product_id"].nunique())
print(df["category"].nunique())
print(df["sub_category"].nunique())
print(df["region"].nunique())
print(df["market"].nunique())
print(df["ship_mode"].nunique())
print(df["order_id"].nunique())
print(len(df))
df.groupby("order_id").size().sort_values(ascending=False).head()
print(df)
print(df["Clean_order_date"].min())
print(df["Clean_order_date"].max())
print(df["Clean_Ship_Date"].min())
print(df["Clean_Ship_Date"].max())
print(df[df["profit"]<0])
print(df[df["customer_name"].isna()])